### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by carlocardella** [carlocardella/vscode-VirtualGists#16]

**Comment by Ahmed-E-86** [comment]
Any progress? I had to use GistPad to upload multiple files.

**Comment by carlocardella** [comment]
I didn't spend much time on this extension lately; I need to find a workaround for a limitation with octokit but I'll bet back to this; thanks for using the extension though

**Comment by Ahmed-E-86** [comment]
> I didn't spend much time on this extension lately; I need to find a workaround for a limitation with octokit but I'll bet back to this; thanks for using the extension though

Thanks for your reply, and thanks for this great extension. I imported all the files using GistPad, then revoked its access. My only problem now is renaming the created gists.

**Comment by carlocardella** [comment]
https://github.com/carlocardella/vscode-VirtualGists/issues/51

**Comment by carlocardella** [comment]
Fixed with 0032aa526162f546b84c10e5f5be3fe15369dda6; version 0.6.0 should be soon available in the [Marketplace](https://marketplace.visualstudio.com/items?itemName=carlocardella.vscode-virtualgists)

**Comment by Ahmed-E-86** [comment]
> Fixed with [0032aa5](https://github.com/carlocardella/vscode-VirtualGists/commit/0032aa526162f546b84c10e5f5be3fe15369dda6); version 0.6.0 should be soon available in the [Marketplace](https://marketplace.visualstudio.com/items?itemName=carlocardella.vscode-virtualgists)

That is amazing! Thank you for your support.
