### ISSUE TITLE
Update gist description

### ISSUE THREAD

**Issue by carlocardella** [carlocardella/vscode-VirtualGists#52]
https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28#update-a-gist

**Comment by carlocardella** [comment]
@Ahmed-E-86 this should address your comment https://github.com/carlocardella/vscode-VirtualGists/issues/16#issuecomment-1859726556

> My only problem now is renaming the created gists.

Version 0.7.0 should be available in the Marketplace soon.

**Comment by Ahmed-E-86** [comment]
> @Ahmed-E-86 this should address your comment [#16 (comment)](https://github.com/carlocardella/vscode-VirtualGists/issues/16#issuecomment-1859726556)
> 
> > My only problem now is renaming the created gists.
> 
> Version 0.7.0 should be available in the Marketplace soon.

That is great news. Thanks for your support.
