### ISSUE TITLE
File corruption after changing file extension

### ISSUE THREAD

**Issue by Ahmed-E-86** [carlocardella/vscode-VirtualGists#53]
I discovered an ugly bug after renaming a file ends with `.py` to `.md`:
The text in the renamed file is gone, and it is replaced by the hash of the file or the encryption of the file, I do not know what is that exactly.

**Here is a screenshot of the issue:**

![Screenshot from 2023-12-22 17-18-01](https://github.com/carlocardella/vscode-VirtualGists/assets/29783425/519e5ed0-d34d-4e90-8e3e-e2f1811e061d)

**Comment by carlocardella** [comment]
Thanks, I'll investigate this. 

Is the file in GitHub (if you check from the browser) actually updated with the hash? 
I have seen a problem like this but it was only affecting the editor in VSCode but the actual file was still correct. 
What happens if you refresh the gist?

**Comment by carlocardella** [comment]
One more question: was the file open in the editor when you renamed it?
Were you able to recover the content, maybe pressing CTRL+Z?

**Comment by carlocardella** [comment]
Ok, I can repro the problem, I'll release a fix asap

**Comment by carlocardella** [comment]
@Ahmed-E-86 this should be fixed in version 0.7.1, I can no longer reproduce.
Let me know if it works for you as well

**Comment by Ahmed-E-86** [comment]
> @Ahmed-E-86 this should be fixed in version 0.7.1, I can no longer reproduce. Let me know if it works for you as well

That was pretty quick! Thank you for your generous support.

 I changed the file extension from .py to .md back and forth multiple times, and I have not encountered any issues.
